<a href="https://colab.research.google.com/github/sunny0625/CoLab/blob/code/Customer_Revenue_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


In [3]:
import tensorflow as tf
tf.__version__

'2.15.0'

# Creating Tensors
1. List
2. Array (NumPy)
3. TensorFlow (Contanst)

In [4]:
my_list = [1, 2, 3, 4, 5]
type(my_list)

list

In [5]:
# Converting Data Type using TF
tf_list = tf.convert_to_tensor(my_list, dtype=tf.float32)

In [6]:
type(tf_list)

tensorflow.python.framework.ops.EagerTensor

In [7]:
my_list = [[1, 2, 3, 4, 5]]
my_list

[[1, 2, 3, 4, 5]]

In [8]:
tf_list1 = tf.convert_to_tensor(my_list,dtype=tf.float32)

In [9]:
print(tf_list)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [10]:
print(tf_list1)

tf.Tensor([[1. 2. 3. 4. 5.]], shape=(1, 5), dtype=float32)


In [11]:
my_list_col = [[1], [2], [3], [4], [5]]
tf_list2 = tf.convert_to_tensor(my_list_col,dtype=tf.float32)
print(tf_list2)

tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]], shape=(5, 1), dtype=float32)


In [12]:
# NumPy Array
import numpy as np

In [13]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [14]:
tf_arr = tf.convert_to_tensor(arr,dtype=tf.float32)
print(tf_arr)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [15]:
# 2 x 2
arr1 = np.array([[1, 2], [3, 4]])
arr1

array([[1, 2],
       [3, 4]])

In [16]:
type(arr1)

numpy.ndarray

In [17]:
tf_arr1 = tf.convert_to_tensor(arr1)
print(tf_arr1)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# Constant

In [18]:
tf_const = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
print(tf_const)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [20]:
tf_const1 = tf.constant(np.array([[1, 2], [3, 4]]))
tf_const1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>