<a href="https://colab.research.google.com/github/sunny0625/CoLab/blob/code/Customer_Revenue_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import tensorflow as tf
tf.__version__

'2.14.0'

# Creating Tensors
1. List
2. Array (NumPy)
3. TensorFlow (Contanst)

In [ ]:
my_list = [1, 2, 3, 4, 5]
type(my_list)

list

In [ ]:
# Converting Data Type using TF
tf_list = tf.convert_to_tensor(my_list, dtype=tf.float32)

In [ ]:
type(tf_list)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
my_list = [[1, 2, 3, 4, 5]]
my_list

[[1, 2, 3, 4, 5]]

In [ ]:
tf_list1 = tf.convert_to_tensor(my_list,dtype=tf.float32)

In [ ]:
print(tf_list)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [ ]:
print(tf_list1)

tf.Tensor([[1. 2. 3. 4. 5.]], shape=(1, 5), dtype=float32)


In [ ]:
my_list_col = [[1], [2], [3], [4], [5]]
tf_list2 = tf.convert_to_tensor(my_list_col,dtype=tf.float32)
print(tf_list2)

tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]], shape=(5, 1), dtype=float32)


In [ ]:
# NumPy Array
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
tf_arr = tf.convert_to_tensor(arr,dtype=tf.float32)
print(tf_arr)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [ ]:
# 2 x 2
arr1 = np.array([[1, 2], [3, 4]])
arr1

array([[1, 2],
       [3, 4]])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
tf_arr1 = tf.convert_to_tensor(arr1)
print(tf_arr1)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


# Constant

In [ ]:
tf_const = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
print(tf_const)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [ ]:
tf_const1 = tf.constant(np.array())